// <auto-generated />
namespace VideoRentalStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _18yearsValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18yearsValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201701210035280_18yearsValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
